# These are supported funding model platforms

github: [shogo4405] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ["https://www.paypal.me/shogo4405"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
