# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

desc "[CI] Review PullRequest."
lane :review do
  spm(
    command: "test",
    package_path: "HaishinKit",
  )
  spm(
    command: "test",
    package_path: "SRTHaishinKit",
  )
  begin
    danger(
      danger_id: 'danger',
      dangerfile: 'Dangerfile',
      verbose: true
    )
  rescue
  end
end

desc "Creates documents."
lane :document do |options|
  if options[:version] == ""
    UI.error("Version is a required argument!")
    next
  end

  version = options[:version]

  sh "rm -rf ../../docs.haishinkit.com/swift/#{version}"
  sh <<COMMAND
 swift package --allow-writing-to-directory ../../docs.haishinkit.com/ generate-documentation --hosting-base-path swift/#{version}\
 --output-path ../../docs.haishinkit.com/swift/#{version}\
 --transform-for-static-hosting\
 --enable-experimental-combined-documentation 
COMMAND

  sh "rm -rf ../../docs.haishinkit.com/swift/latest"
  sh <<COMMAND
 swift package --allow-writing-to-directory ../../docs.haishinkit.com/ generate-documentation --hosting-base-path swift/latest\
 --output-path ../../docs.haishinkit.com/swift/latest\
 --transform-for-static-hosting\
 --enable-experimental-combined-documentation  
COMMAND
end
