# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

desc "[CI] Review PullRequest."
lane :review do
  spm(
    command: "test",
    package_path: "HaishinKit",
  )
  spm(
    command: "test",
    package_path: "SRTHaishinKit",
  )
  begin
    danger(
      danger_id: 'danger',
      dangerfile: 'Dangerfile',
      verbose: true
    )
  rescue
  end
end

desc "Creates documents."
lane :document do
  sh('cd ../ && sourcekitten doc --spm --module-name HaishinKit > HaishinKit.json && sourcekitten doc --spm --module-name SRTHaishinKit > SRTHaishinKit.json && jazzy --sourcekitten-sourcefile HaishinKit.json,SRTHaishinKit.json')
end
