# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

desc "[CI] Review PullRequest."
lane :review do
  spm
  carthage(
    use_xcframeworks: true,
    platform: 'iOS'
  ) if Helper.is_ci?
  scan(scheme: 'Tests')
end

desc "Creates documents."
lane :document do
  sh('cd ../ && swift package --allow-writing-to-directory ./docs generate-documentation --target HaishinKit --disable-indexing --hosting-base-path HaishinKit.swift --output-path ./docs')
end
