
platform :ios, '13.0'


target 'newVideo' do
    use_frameworks! #SDK依赖

    pod 'TFGPUImage', :path => '../../TFGPUImage/TFGPUImage.podspec'
    pod 'TFSRT', :path => '../../HaishinKit.swift/TFSRT.podspec'
    
end


#  适配xcode 14.3
post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
